CREATE TABLE socio (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(150) NOT NULL,
    documento varchar(20) NOT NULL UNIQUE,
    contacto varchar(255)
);

CREATE TABLE galpon (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(100) NOT NULL,
    capacidad_gallinas integer NOT NULL CHECK (capacidad_gallinas > 0),
    estado varchar(20) NOT NULL CHECK (estado IN ('activo', 'inactivo', 'mantenimiento'))
);

CREATE TABLE categoria_peso (
    codigo varchar(10) PRIMARY KEY,
    nombre varchar(30) NOT NULL,
    peso_min_g integer,
    peso_max_g integer
);

CREATE TABLE mayorista (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(150) NOT NULL,
    ubicacion varchar(150),
    contacto json
);

CREATE TABLE rol (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(50) NOT NULL UNIQUE
);

CREATE TABLE permiso (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo varchar(50) NOT NULL UNIQUE,
    descripcion varchar(150) NOT NULL
);

CREATE TABLE invierte_en (
    id_socio integer NOT NULL,
    id_galpon integer NOT NULL,
    porcentaje_inversion numeric(5, 2) NOT NULL
        CHECK (porcentaje_inversion >= 25.00 AND porcentaje_inversion <= 100.00),
    PRIMARY KEY (id_socio, id_galpon),
    CONSTRAINT fk_invierte_en_socio
        FOREIGN KEY (id_socio) REFERENCES socio (id) ON DELETE CASCADE,
    CONSTRAINT fk_invierte_en_galpon
        FOREIGN KEY (id_galpon) REFERENCES galpon (id) ON DELETE CASCADE
);

CREATE TABLE log_conteo (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp timestamp NOT NULL,
    cantidad integer NOT NULL,
    id_galpon integer NOT NULL,
    codigo_categoria_peso varchar(10) NOT NULL,
    CONSTRAINT fk_log_conteo_galpon
        FOREIGN KEY (id_galpon) REFERENCES galpon (id) ON DELETE RESTRICT,
    CONSTRAINT fk_log_conteo_categoria
        FOREIGN KEY (codigo_categoria_peso) REFERENCES categoria_peso (codigo) ON DELETE RESTRICT
);

CREATE TABLE cierre_diario (
    id_galpon integer NOT NULL,
    codigo_categoria_peso varchar(10) NOT NULL,
    fecha date NOT NULL,
    cantidad_bandejas integer NOT NULL CHECK (cantidad_bandejas >= 0),
    PRIMARY KEY (id_galpon, codigo_categoria_peso, fecha),
    CONSTRAINT fk_cierre_diario_galpon
        FOREIGN KEY (id_galpon) REFERENCES galpon (id) ON DELETE RESTRICT,
    CONSTRAINT fk_cierre_diario_categoria
        FOREIGN KEY (codigo_categoria_peso) REFERENCES categoria_peso (codigo) ON DELETE RESTRICT
);

CREATE TABLE bodega (
    codigo_categoria_peso varchar(10) NOT NULL,
    fecha_corte date NOT NULL,
    cantidad_bandejas integer NOT NULL CHECK (cantidad_bandejas >= 0),
    PRIMARY KEY (codigo_categoria_peso, fecha_corte),
    CONSTRAINT fk_bodega_categoria
        FOREIGN KEY (codigo_categoria_peso) REFERENCES categoria_peso (codigo) ON DELETE RESTRICT
);

CREATE TABLE precio (
    id_mayorista integer NOT NULL,
    codigo_categoria_peso varchar(10) NOT NULL,
    valor_unitario numeric(10, 2) NOT NULL CHECK (valor_unitario > 0),
    PRIMARY KEY (id_mayorista, codigo_categoria_peso),
    CONSTRAINT fk_precio_mayorista
        FOREIGN KEY (id_mayorista) REFERENCES mayorista (id) ON DELETE CASCADE,
    CONSTRAINT fk_precio_categoria
        FOREIGN KEY (codigo_categoria_peso) REFERENCES categoria_peso (codigo) ON DELETE RESTRICT
);

CREATE TABLE pedido (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha date NOT NULL,
    estado varchar(20) NOT NULL
        CHECK (estado IN ('pendiente', 'cargado', 'entregado', 'modificado', 'cancelado')),
    id_mayorista integer NOT NULL,
    CONSTRAINT fk_pedido_mayorista
        FOREIGN KEY (id_mayorista) REFERENCES mayorista (id) ON DELETE RESTRICT
);

CREATE TABLE detalle_pedido (
    id_pedido integer NOT NULL,
    codigo_categoria_peso varchar(10) NOT NULL,
    cantidad_solicitada integer NOT NULL CHECK (cantidad_solicitada >= 0),
    PRIMARY KEY (id_pedido, codigo_categoria_peso),
    CONSTRAINT fk_detalle_pedido_pedido
        FOREIGN KEY (id_pedido) REFERENCES pedido (id) ON DELETE CASCADE,
    CONSTRAINT fk_detalle_pedido_categoria
        FOREIGN KEY (codigo_categoria_peso) REFERENCES categoria_peso (codigo) ON DELETE RESTRICT
);

CREATE TABLE venta (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora timestamp NOT NULL,
    id_pedido integer NOT NULL UNIQUE,
    CONSTRAINT fk_venta_pedido
        FOREIGN KEY (id_pedido) REFERENCES pedido (id) ON DELETE RESTRICT
);

CREATE TABLE detalle_venta (
    id_venta integer NOT NULL,
    codigo_categoria_peso varchar(10) NOT NULL,
    cantidad_vendida integer NOT NULL CHECK (cantidad_vendida >= 0),
    precio_aplicado numeric(10, 2) NOT NULL CHECK (precio_aplicado > 0),
    PRIMARY KEY (id_venta, codigo_categoria_peso),
    CONSTRAINT fk_detalle_venta_venta
        FOREIGN KEY (id_venta) REFERENCES venta (id) ON DELETE CASCADE,
    CONSTRAINT fk_detalle_venta_categoria
        FOREIGN KEY (codigo_categoria_peso) REFERENCES categoria_peso (codigo) ON DELETE RESTRICT
);

CREATE TABLE usuario (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(100) NOT NULL,
    login varchar(50) NOT NULL UNIQUE,
    telefono varchar(20),
    password_hash varchar(255) NOT NULL,
    id_rol integer NOT NULL,
    CONSTRAINT fk_usuario_rol
        FOREIGN KEY (id_rol) REFERENCES rol (id) ON DELETE RESTRICT
);

CREATE TABLE rol_permiso (
    id_rol integer NOT NULL,
    id_permiso integer NOT NULL,
    PRIMARY KEY (id_rol, id_permiso),
    CONSTRAINT fk_rol_permiso_rol
        FOREIGN KEY (id_rol) REFERENCES rol (id) ON DELETE CASCADE,
    CONSTRAINT fk_rol_permiso_permiso
        FOREIGN KEY (id_permiso) REFERENCES permiso (id) ON DELETE CASCADE
);

CREATE TABLE auditoria (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario integer NOT NULL,
    tabla_afectada varchar(50) NOT NULL,
    id_registro_afectado varchar(50) NOT NULL,
    accion varchar(20) NOT NULL CHECK (accion IN ('INSERT', 'UPDATE', 'DELETE')),
    datos_anteriores json,
    datos_nuevos json,
    fecha_hora timestamp NOT NULL DEFAULT now(),
    ip_origen varchar(45),
    resultado varchar(20) NOT NULL CHECK (resultado IN ('EXITOSO', 'FALLIDO')),
    CONSTRAINT fk_auditoria_usuario
        FOREIGN KEY (id_usuario) REFERENCES usuario (id) ON DELETE RESTRICT
);

CREATE INDEX idx_log_conteo_galpon_categoria_timestamp
    ON log_conteo (id_galpon, codigo_categoria_peso, timestamp);
CREATE INDEX idx_cierre_diario_fecha
    ON cierre_diario (fecha);
CREATE INDEX idx_bodega_fecha_corte
    ON bodega (fecha_corte);
CREATE INDEX idx_pedido_fecha
    ON pedido (fecha);
CREATE INDEX idx_pedido_mayorista
    ON pedido (id_mayorista);
CREATE INDEX idx_venta_fecha_hora
    ON venta (fecha_hora);
CREATE INDEX idx_auditoria_tabla_registro
    ON auditoria (tabla_afectada, id_registro_afectado);
CREATE INDEX idx_auditoria_fecha_hora
    ON auditoria (fecha_hora);