CREATE TABLE socio (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(150) NOT NULL,
    documento varchar(20) NOT NULL UNIQUE,
    contacto json
);

CREATE TABLE galpon (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(100) NOT NULL,
    gallinas_actuales integer NOT NULL CHECK (gallinas_actuales >= 0),
    estado varchar(20) NOT NULL CHECK (estado IN ('activo', 'inactivo', 'mantenimiento'))
);

CREATE TABLE categoria_peso (
    codigo varchar(10) PRIMARY KEY,
    nombre varchar(30) NOT NULL,
    peso_min_g integer,
    peso_max_g integer
);

CREATE TABLE mayorista (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(150) NOT NULL,
    ubicacion varchar(150),
    contacto json
);

CREATE TABLE rol (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(50) NOT NULL UNIQUE
);

CREATE TABLE permiso (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo varchar(50) NOT NULL UNIQUE,
    descripcion varchar(150) NOT NULL
);

CREATE TABLE inversion_socio (
    id_socio integer NOT NULL,
    id_galpon integer NOT NULL,
    porcentaje_inversion numeric(5, 2) NOT NULL
        CHECK (porcentaje_inversion >= 25.00 AND porcentaje_inversion <= 100.00),
    PRIMARY KEY (id_socio, id_galpon),
    CONSTRAINT fk_inversion_socio_socio
        FOREIGN KEY (id_socio) REFERENCES socio (id) ON DELETE CASCADE,
    CONSTRAINT fk_inversion_socio_galpon
        FOREIGN KEY (id_galpon) REFERENCES galpon (id) ON DELETE CASCADE
);

CREATE TABLE log_conteo (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp timestamp NOT NULL,
    cantidad integer NOT NULL,
    id_galpon integer NOT NULL,
    codigo_categoria_peso varchar(10) NOT NULL,
    CONSTRAINT fk_log_conteo_galpon
        FOREIGN KEY (id_galpon) REFERENCES galpon (id) ON DELETE RESTRICT,
    CONSTRAINT fk_log_conteo_categoria
        FOREIGN KEY (codigo_categoria_peso) REFERENCES categoria_peso (codigo) ON DELETE RESTRICT,
    CONSTRAINT ck_log_conteo_cantidad
        CHECK (cantidad IN (-1, 1))
);

CREATE TABLE cierre_diario (
    id_galpon integer NOT NULL,
    codigo_categoria_peso varchar(10) NOT NULL,
    fecha date NOT NULL,
    cantidad_bandejas integer NOT NULL CHECK (cantidad_bandejas >= 0),
    cantidad_sobrante integer NOT NULL DEFAULT 0 CHECK (cantidad_sobrante >= 0 AND cantidad_sobrante < 30),
    PRIMARY KEY (id_galpon, codigo_categoria_peso, fecha),
    CONSTRAINT fk_cierre_diario_galpon
        FOREIGN KEY (id_galpon) REFERENCES galpon (id) ON DELETE RESTRICT,
    CONSTRAINT fk_cierre_diario_categoria
        FOREIGN KEY (codigo_categoria_peso) REFERENCES categoria_peso (codigo) ON DELETE RESTRICT
);

CREATE TABLE bodega (
    id_galpon integer NOT NULL,
    codigo_categoria_peso varchar(10) NOT NULL,
    fecha_corte date NOT NULL,
    cantidad_bandejas integer NOT NULL CHECK (cantidad_bandejas >= 0),
    PRIMARY KEY (id_galpon, codigo_categoria_peso, fecha_corte),
    CONSTRAINT fk_bodega_galpon
        FOREIGN KEY (id_galpon) REFERENCES galpon (id) ON DELETE RESTRICT,
    CONSTRAINT fk_bodega_categoria
        FOREIGN KEY (codigo_categoria_peso) REFERENCES categoria_peso (codigo) ON DELETE RESTRICT
);

CREATE TABLE precio (
    id_mayorista integer NOT NULL,
    codigo_categoria_peso varchar(10) NOT NULL,
    valor_unitario numeric(10, 2) NOT NULL CHECK (valor_unitario > 0),
    PRIMARY KEY (id_mayorista, codigo_categoria_peso),
    CONSTRAINT fk_precio_mayorista
        FOREIGN KEY (id_mayorista) REFERENCES mayorista (id) ON DELETE CASCADE,
    CONSTRAINT fk_precio_categoria
        FOREIGN KEY (codigo_categoria_peso) REFERENCES categoria_peso (codigo) ON DELETE RESTRICT
);

CREATE TABLE gasto (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concepto varchar(150) NOT NULL,
    valor numeric(10, 2) NOT NULL CHECK (valor > 0)
);

CREATE TABLE pedido (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha timestamp NOT NULL,
    estado varchar(20) NOT NULL
        CHECK (estado IN ('pendiente', 'cargado', 'entregado', 'modificado', 'cancelado')),
    id_mayorista integer NOT NULL,
    CONSTRAINT fk_pedido_mayorista
        FOREIGN KEY (id_mayorista) REFERENCES mayorista (id) ON DELETE RESTRICT
);

CREATE TABLE detalle_pedido (
    id_pedido integer NOT NULL,
    codigo_categoria_peso varchar(10) NOT NULL,
    cantidad_solicitada integer NOT NULL CHECK (cantidad_solicitada >= 0),
    PRIMARY KEY (id_pedido, codigo_categoria_peso),
    CONSTRAINT fk_detalle_pedido_pedido
        FOREIGN KEY (id_pedido) REFERENCES pedido (id) ON DELETE CASCADE,
    CONSTRAINT fk_detalle_pedido_categoria
        FOREIGN KEY (codigo_categoria_peso) REFERENCES categoria_peso (codigo) ON DELETE RESTRICT
);

CREATE TABLE venta (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora timestamp NOT NULL,
    id_pedido integer NOT NULL UNIQUE,
    CONSTRAINT fk_venta_pedido
        FOREIGN KEY (id_pedido) REFERENCES pedido (id) ON DELETE RESTRICT
);

CREATE TABLE detalle_venta (
    id_venta integer NOT NULL,
    codigo_categoria_peso varchar(10) NOT NULL,
    cantidad_vendida integer NOT NULL CHECK (cantidad_vendida >= 0),
    precio_aplicado numeric(10, 2) NOT NULL CHECK (precio_aplicado > 0),
    PRIMARY KEY (id_venta, codigo_categoria_peso),
    CONSTRAINT fk_detalle_venta_venta
        FOREIGN KEY (id_venta) REFERENCES venta (id) ON DELETE CASCADE,
    CONSTRAINT fk_detalle_venta_categoria
        FOREIGN KEY (codigo_categoria_peso) REFERENCES categoria_peso (codigo) ON DELETE RESTRICT
);

CREATE TABLE usuario (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(100) NOT NULL,
    login varchar(50) NOT NULL UNIQUE,
    password_hash varchar(255) NOT NULL,
    contacto json,
    id_rol integer NOT NULL,
    CONSTRAINT fk_usuario_rol
        FOREIGN KEY (id_rol) REFERENCES rol (id) ON DELETE RESTRICT
);

CREATE TABLE rol_permiso (
    id_rol integer NOT NULL,
    id_permiso integer NOT NULL,
    PRIMARY KEY (id_rol, id_permiso),
    CONSTRAINT fk_rol_permiso_rol
        FOREIGN KEY (id_rol) REFERENCES rol (id) ON DELETE CASCADE,
    CONSTRAINT fk_rol_permiso_permiso
        FOREIGN KEY (id_permiso) REFERENCES permiso (id) ON DELETE CASCADE
);

CREATE TABLE auditoria (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario integer NOT NULL,
    tabla_afectada varchar(50) NOT NULL,
    id_registro_afectado varchar(50) NOT NULL,
    accion varchar(20) NOT NULL CHECK (accion IN ('INSERT', 'UPDATE', 'DELETE')),
    datos_anteriores json,
    datos_nuevos json,
    fecha_hora timestamp NOT NULL DEFAULT now(),
    ip_origen varchar(45),
    resultado varchar(20) NOT NULL CHECK (resultado IN ('EXITOSO', 'FALLIDO')),
    CONSTRAINT fk_auditoria_usuario
        FOREIGN KEY (id_usuario) REFERENCES usuario (id) ON DELETE RESTRICT
);

CREATE INDEX idx_log_conteo_galpon_categoria_timestamp
    ON log_conteo (id_galpon, codigo_categoria_peso, timestamp);
CREATE INDEX idx_cierre_diario_fecha
    ON cierre_diario (fecha);
CREATE INDEX idx_bodega_fecha_corte
    ON bodega (fecha_corte);
CREATE INDEX idx_pedido_fecha
    ON pedido (fecha);
CREATE INDEX idx_pedido_mayorista
    ON pedido (id_mayorista);
CREATE INDEX idx_venta_fecha_hora
    ON venta (fecha_hora);
CREATE INDEX idx_auditoria_tabla_registro
    ON auditoria (tabla_afectada, id_registro_afectado);
CREATE INDEX idx_auditoria_fecha_hora
    ON auditoria (fecha_hora);

-- Registros Iniciales

INSERT INTO socio (nombre, documento, contacto) VALUES
('Mauricio', '123456789', '{"telefono": "3001234567", "email": "mauricio@example.com"}'),
('J.C.V', '987654321', '{"telefono": "3008976481", "email": "jcv@example.com"}'),
('L.F.D', '456789123', '{"telefono": "3004567891", "email": "lfd@example.com"}'),
('M.F.D', '321654987', '{"telefono": "3003216549", "email": "mfd@example.com"}'),
('Oscar', '654987321', '{"telefono": "3116549873", "email": "oscar@example.com"}'),
('Paty', '789123456', '{"telefono": "3117891234", "email": "paty@example.com"}'),
('L. Marina', '159753486', '{"telefono": "3111597534", "email": "lmarina@example.com"}'),
('Magolita', '753159486', '{"telefono": "3117531594", "email": "magolita@example.com"}'),
('Marthica', '951357486', '{"telefono": "3119513574", "email": "marthica@example.com"}');

INSERT INTO galpon (nombre, gallinas_actuales, estado) VALUES
('Galpón 1', 2260, 'activo'),
('Galpón 2', 0, 'inactivo'),
('Galpón 3', 2300, 'activo'),
('Galpón 4', 2240, 'activo'),
('Galpón 5', 2350, 'activo');

INSERT INTO categoria_peso (codigo, nombre, peso_min_g, peso_max_g) VALUES
('Y', 'Yumbo', 78, null),
('Ex', 'Extra', 67, 77),
('AA', 'AA', 60, 66),
('A', 'A', 53, 59),
('B', 'B', 46, 52),
('C', 'C', 45, 45),
('P', 'Pipo', null, 45),
('Q', 'Quebrado', null, null);

INSERT INTO mayorista (nombre, ubicacion, contacto) VALUES
('Deyanira', 'Calle 123, La Plata, Huila', '{"telefono": "3196487561"}'),
('Ferney', 'Carrera 45, Neiva, Huila', '{"telefono": "3109876543"}'),
('Nidia', 'Avenida 78, Garzón, Huila', '{"telefono": "3151234567"}'),
('C. Andrés', 'Calle 56, Pitalito, Huila', '{"telefono": "3204567891"}'),
('Jaime', 'Calle 34, La Plata, Huila', '{"telefono": "3119876543"}'),
('Carolina', 'Carrera 12, Neiva, Huila', '{"telefono": "3123456789"}'),
('Humberto', 'Avenida 90, Garzón, Huila', '{"telefono": "3134567890"}'),
('Orlando', 'Calle 78, Pitalito, Huila', '{"telefono": "3145678901"}'),
('América', 'Carrera 34, La Plata, Huila', '{"telefono": "3156789012"}'),
('Económico', 'Avenida 56, Neiva, Huila', '{"telefono": "3167890123"}'),
('Wilmer', 'Calle 90, Garzón, Huila', '{"telefono": "3178901234"}');

INSERT INTO rol (nombre) VALUES
('Administrador'),
('Galponero'),
('Vendedor');

INSERT INTO permiso (codigo, descripcion) VALUES
('VER_PRODUCCION', 'Ver registros de producción diaria por galpón'),
('INGRESAR_PEDIDO', 'Registrar el pedido de un mayorista'),
('REGISTRAR_VENTA', 'Registrar la venta de un pedido'),
('EDITAR_PRECIOS', 'Modificar los precios de venta por peso y por mayorista'),
('GESTIONAR_USUARIOS', 'Gestionar usuarios y roles del sistema'),
('GESTIONAR_INVENTARIO', 'Modificar el inventario de insumos'),
('INGRESAR_GASTO', 'Registrar un gasto de operación'),
('VER_CIERRE', 'Ver el cierre semanal de producción, ventas, gastos y saldo'),
('INGRESAR_CONTEO', 'Registrar unidades de huevos o bandejas en el conteo diario de manera manual'),
('REGISTRAR_CIERRE_DIARIO', 'Registrar el cierre diario de producción por galpón'),
('GESTIONAR_SOCIOS', 'Gestionar socios y sus inversiones en galpones'),
('GESTIONAR_MAYORISTAS', 'Gestionar mayoristas y sus datos de contacto'),
('GESTIONAR_GALPONES', 'Gestionar galpones y su estado de operación');

INSERT INTO rol_permiso (id_rol, id_permiso) VALUES
-- Administrador (id=1)
(1,  1),  -- VER_PRODUCCION
(1,  2),  -- INGRESAR_PEDIDO
(1,  3),  -- REGISTRAR_VENTA
(1,  4),  -- EDITAR_PRECIOS
(1,  5),  -- GESTIONAR_USUARIOS
(1,  6),  -- GESTIONAR_INVENTARIO
(1,  7),  -- INGRESAR_GASTO
(1,  8),  -- VER_CIERRE
(1,  9),  -- INGRESAR_CONTEO
(1, 10),  -- REGISTRAR_CIERRE_DIARIO
(1, 11),  -- GESTIONAR_SOCIOS
(1, 12),  -- GESTIONAR_MAYORISTAS
(1, 13),  -- GESTIONAR_GALPONES
-- Galponero (id=2)
(2,  1),  -- VER_PRODUCCION
(2,  6),  -- GESTIONAR_INVENTARIO
(2,  7),  -- INGRESAR_GASTO
(2,  8),  -- VER_CIERRE
(2,  9),  -- INGRESAR_CONTEO
(2, 10),  -- REGISTRAR_CIERRE_DIARIO
-- Vendedor (id=3)
(3,  1),  -- VER_PRODUCCION
(3,  2),  -- INGRESAR_PEDIDO
(3,  3),  -- REGISTRAR_VENTA
(3,  7),  -- INGRESAR_GASTO
(3,  8),  -- VER_CIERRE
(3, 12);  -- GESTIONAR_MAYORISTAS

INSERT INTO inversion_socio (id_socio, id_galpon, porcentaje_inversion) VALUES
(1, 1, 25),
(2, 1, 25),
(3, 1, 25),
(4, 1, 25),
(5, 3, 50),
(6, 3, 25),
(7, 3, 25),
(5, 4, 50),
(8, 4, 25),
(3, 4, 25),
(1, 5, 50),
(9, 5, 25),
(4, 5, 25);

INSERT INTO precio (id_mayorista, codigo_categoria_peso, valor_unitario) VALUES
(1, 'AA', 14000),
(1, 'A', 13000),
(2, 'A', 11500),
(2, 'C', 7000),
(2, 'P', 6500),
(3, 'Ex', 15000),
(3, 'AA', 13000),
(3, 'A', 12000),
(3, 'B', 11000),
(3, 'C', 7000),
(4, 'Y', 20000),
(4, 'Ex', 14000),
(4, 'AA', 13000),
(4, 'A', 12000),
(4, 'B', 11000);

INSERT INTO gasto (concepto, valor) VALUES
('Chana', 240000),
('Salario Humberto', 225000),
('Salario Ayudante', 105000),
('Provisión', 120000),
('Salario Carlos Andrés', 799998);

INSERT INTO usuario (nombre, login, password_hash, contacto, id_rol) VALUES
('Administrador', 'admin', '$2a$12$5hafiSCE.98sXCRkMvXMU.FxWUjb1FpNgl6Dh5CUrU73U7ZZk2YqS', '{"telefono": "3007778861"}', 1), -- pass: 123
('Galponero', 'galponero', '$2a$12$FHHY8hDo6xxu6mYC8..AJ.NxtwfkD9.HZqxz4xXPLcbESFAIsT04q', '{"telefono": "3007778862"}', 2), -- pass: galponero
('Vendedor', 'vendedor', '$2a$12$tNcG4PWFfUuHT3vj5affx.v2S1osWBtTgE.oYqvDLoVd3fPWtLJfm', '{"telefono": "3007778863"}', 3); -- pass: vendedor
